version: "3.9"
services:
  # --- БАЗА ДАННЫХ ПСКЛ---
  postgres:
    image: postgres:17
    container_name: dayzDB
    ports: [ "5432:5432" ]
    env_file: [ .env ]
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
  # --- БЭК ---
  backend:
    build: ../backend
    volumes:
      - ../backend:/app
      - /app/node_modules
    container_name: dayz_backend
    ports: ["4000:4000"]
    env_file: [ .env ]
    stdin_open: true
    tty: true
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
    command: npm run dev
    restart: unless-stopped
  # --- фронт ---
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: dayz_frontend
    ports: ["5173:5173"]
    volumes:
     - ../frontend:/app
     - /app/node_modules
    environment:
     - VITE_API_URL=http://localhost:4000
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped
